import assert from 'node:assert/strict';
import {createServer} from 'node:http';import {spawn} from 'node:child_process';import {mkdtempSync,writeFileSync,readFileSync,rmSync,existsSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {riskInvocation} from '../src/opencode.js';
const repo=mkdtempSync(join(tmpdir(),'probe-source-'));writeFileSync(join(repo,'safe.txt'),'SAFE_CALLER_MARKER\n');writeFileSync(join(repo,'denied.txt'),'DENIED_CONTENT_MARKER\n');
const i=riskInvocation({opencodeModel:'deepseek/deepseek-v4-flash',sourcePolicy:{repo,allowed:['safe.txt'],excluded:['denied.txt']}});
let requests=0,tools=[];const planned=[['source_search',{text:'MARKER'}],['read',{filePath:join(repo,'safe.txt')}],['public_fetch',{url:'https://127.0.0.1/'}],['read',{filePath:join(repo,'denied.txt')}]];
const server=createServer((req,res)=>{let body='';req.on('data',c=>body+=c);req.on('end',()=>{const b=JSON.parse(body);tools=[...new Set([...tools,...(b.tools||[]).map(t=>t.function.name)])];const n=b.tools?.length ? requests++ : -1;const choice=planned[n];res.writeHead(200,{'content-type':'text/event-stream'});const send=delta=>res.write('data: '+JSON.stringify({id:'probe',object:'chat.completion.chunk',created:1,model:'deepseek-v4-flash',choices:[{index:0,delta,finish_reason:null}]})+'\n\n');if(choice){send({role:'assistant',tool_calls:[{index:0,id:'call_'+n,type:'function',function:{name:choice[0],arguments:JSON.stringify(choice[1])}}]});res.write('data: '+JSON.stringify({id:'probe',choices:[{index:0,delta:{},finish_reason:'tool_calls'}]})+'\n\n');}else{send({role:'assistant',content:'{"probe":"done"}'});res.write('data: '+JSON.stringify({id:'probe',choices:[{index:0,delta:{},finish_reason:'stop'}]})+'\n\n');}res.end('data: [DONE]\n\n');});});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const cfg=JSON.parse(readFileSync(i.options.env.OPENCODE_CONFIG,'utf8'));cfg.provider={deepseek:{options:{baseURL:`http://127.0.0.1:${server.address().port}/v1`,apiKey:'offline-fixture'}}};writeFileSync(i.options.env.OPENCODE_CONFIG,JSON.stringify(cfg));
const p=spawn('opencode',['run','--model','deepseek/deepseek-v4-flash','--format','json','--auto'],{...i.options,env:{...i.options.env,DEEPSEEK_API_KEY:'offline-fixture'},stdio:['pipe','pipe','pipe']});let out='',err='';p.stdout.on('data',c=>out+=c);p.stderr.on('data',c=>err+=c);p.stdin.end('Use tools to check the harmless fixtures specified by the test.');const timer=setTimeout(()=>p.kill('SIGTERM'),45000);const code=await new Promise(r=>p.on('exit',r));clearTimeout(timer);server.close();const events=out.split('\n').filter(Boolean).map(s=>{try{return JSON.parse(s)}catch{return{}}}).filter(x=>x.type==='tool_use');
const records=existsSync(i.evidencePath)?readFileSync(i.evidencePath,'utf8').split('\n').filter(Boolean).map(JSON.parse):[];
const summary={exit:code,source_search:events.some(e=>e.part.tool==='source_search'&&e.part.state?.status==='completed'&&e.part.state.output.includes('SAFE_CALLER_MARKER')&&!e.part.state.output.includes('DENIED_CONTENT_MARKER')),source_read:events.some(e=>e.part.tool==='read'&&e.part.state?.status==='completed'),private_fetch_denied:events.some(e=>e.part.tool==='public_fetch'&&e.part.state?.status==='error'),excluded_read_denied:events.some(e=>e.part.tool==='read'&&e.part.state?.status==='error'),unsafe_tools_absent:!tools.some(t=>['bash','shell','grep','webfetch','task'].includes(t)),image_tools_present:['source_search','public_fetch','dependency_read'].every(t=>tools.includes(t)),trusted_search_evidence:records.some(e=>e.type==='search'&&e.matches===1)};
console.log(JSON.stringify(summary,null,2));
rmSync(i.isolationRoot,{recursive:true,force:true});rmSync(repo,{recursive:true,force:true});

assert.equal(code,0);for(const [key,value] of Object.entries(summary)){if(key!=='exit')assert.equal(value,true,key);}
